name: poetry

on:
  push

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Install Python poetry
      uses: snok/install-poetry@v1
      with:
        version: 2.0.0
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
        virtualenvs-path: .venv

    - name: Publish Test Results
      if: always()
      run: |
        cat *.log

